[package]
name = "pkpw"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "What if correct horse battery staple, but Pokémon."
readme = "README.md"
homepage = "https://github.com/jbhannah/pkpw"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
