name: "Copilot Setup Steps"

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/copilot-setup-steps.yml
  pull_request:
    paths:
      - .github/workflows/copilot-setup-steps.yml

jobs:
  copilot-setup-steps:
    runs-on: ubuntu-latest
    permissions: {}

    steps:
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
